import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate, NetworkOnly, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by build
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// ============================================
// CACHE FIRST - Static Assets (JS, CSS, fonts)
// ============================================
registerRoute(
  ({ request }) => 
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'font',
  new CacheFirst({
    cacheName: 'static-assets-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// ============================================
// CACHE FIRST - Images (aggressive caching)
// ============================================
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
      }),
    ],
  })
);

// ============================================
// STALE WHILE REVALIDATE - HTML Pages
// ============================================
// Cache HTML pages but serve from network if available
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new StaleWhileRevalidate({
    cacheName: 'pages-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// ============================================
// NETWORK FIRST - API Matches Data
// ============================================
// Try network first for fresh data, fallback to cache
registerRoute(
  ({ url }) => url.pathname === '/api/matches',
  new NetworkFirst({
    cacheName: 'api-matches-v1',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// ============================================
// NETWORK FIRST - API Achievements Data
// ============================================
registerRoute(
  ({ url }) => url.pathname === '/api/achievements',
  new NetworkFirst({
    cacheName: 'api-achievements-v1',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 10 * 60, // 10 minutes
      }),
    ],
  })
);

// ============================================
// NETWORK ONLY - Realtime APIs (NO CACHING)
// ============================================
// CRITICAL: Do NOT cache realtime data
registerRoute(
  ({ url }) => 
    url.pathname.startsWith('/api/live') ||
    url.pathname.includes('socket.io') ||
    url.pathname.startsWith('/socket.io'),
  new NetworkOnly()
);

// ============================================
// CACHE FIRST - Uploaded Match Images
// ============================================
registerRoute(
  ({ url }) => url.pathname.startsWith('/uploads/'),
  new CacheFirst({
    cacheName: 'uploaded-images-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// ============================================
// CACHE FIRST - External Fonts (Google Fonts)
// ============================================
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// ============================================
// CACHE FIRST - Manifest and App Assets
// ============================================
registerRoute(
  ({ url }) => 
    url.pathname.endsWith('manifest.json') ||
    url.pathname.startsWith('/icons/') ||
    url.pathname === '/offline.html',
  new CacheFirst({
    cacheName: 'app-shell-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// ============================================
// OFFLINE FALLBACK
// ============================================
self.addEventListener('fetch', (event) => {
  // Only handle GET requests
  if (event.request.method !== 'GET') {
    return;
  }

  // Fallback to offline page for navigation
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          // Cache successful responses
          if (response && response.status === 200 && response.type === 'basic') {
            const responseToCache = response.clone();
            caches.open('pages-v1').then((cache) => {
              cache.put(event.request, responseToCache);
            });
          }
          return response;
        })
        .catch(() => {
          // Fallback to offline page when offline
          return caches.match('/offline.html');
        })
    );
  }
});

// ============================================
// UPDATE & CLEANUP
// ============================================
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  // Claim all clients to take control immediately
  event.waitUntil(self.clients.claim());
  
  // Delete old caches
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          const validCaches = [
            'static-assets-v1',
            'images-v1',
            'pages-v1',
            'api-matches-v1',
            'api-achievements-v1',
            'uploaded-images-v1',
            'google-fonts-v1',
            'app-shell-v1',
          ];
          if (!validCaches.includes(cacheName)) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});
